### ISSUE TITLE
Will not load on mobile

### ISSUE THREAD

**Issue by Calorion** [Trikzon/obsidian-frontmatter-links#10]
As title. Here's the Console:

![image](https://user-images.githubusercontent.com/3050950/201479608-e18046de-5315-47c1-8438-b5286f18ab1f.jpeg)

**Comment by Trikzon** [comment]
I am investigating this now. It should work on mobile, and I did test it before publishing it, but now it doesn't work

**Comment by Calorion** [comment]
I think it's the same issue as this: https://github.com/swar8080/obsidian-plugin-update-tracker/issues/5

**Comment by Trikzon** [comment]
As far as I can tell, this plugin now works on mobile after the 1.2.5 update.

A possibility is that the previous version was using "regex lookbehinds" and that's not supported on iOS... but tbh I'm not sure what those are (regex was added in a PR for the last version) and a lot of the last version's logic has been rewritten for the new version.

If you still have issues with mobile, reopen this issue.
