### ISSUE TITLE
Could not open vault

### ISSUE THREAD

**Issue by kmaustral** [Trikzon/obsidian-frontmatter-links#13]
After updating this plug in I could not open my vault. I checked the console and there were error messages related to it. I removed it from .obsidian and the vault loaded without a problem. I had 1.2.5

**Comment by Trikzon** [comment]
Could you share the error messages? I haven't gotten this error.

**Comment by kmaustral** [comment]
[image: image.png]

**Comment by Trikzon** [comment]
This should be fixed in 1.2.6. If you still receive this error after updating, or have any more issues, please reopen this issue or create a new issue, respectively. :)

**Comment by kmaustral** [comment]
Many thanks.
