### ISSUE TITLE
Multiple links in one line?

### ISSUE THREAD

**Issue by ReaderGuy42** [Trikzon/obsidian-frontmatter-links#22]
Is there a way to have multiple links in one line?

E.g. 
```
Author: "[[Stephen King]]", "[[J.R.R. Tolkien]]"
```
This works as far as the plugin is concerned, I think, but in reading mode is rendered as `Invalid YAML`

How can I achieve this?

Thanks :)

**Comment by Trikzon** [comment]
It should work like this:
```
Author: ["[[Stephen King]]", "[[J.R.R. Tolkien]]"]
```
or
```
Author: 
- "[[Stephen King]]"
- "[[J.R.R. Tolkien]]"
```

https://www.w3schools.io/file/yaml-arrays/

**Comment by ReaderGuy42** [comment]
Oh, that's perfect, thank you! :)
