### ISSUE TITLE
Support urls not surrounded by quotes

### ISSUE THREAD

**Issue by mnaoumov** [Trikzon/obsidian-frontmatter-links#5]
```
---
url: https://google.com
---
```

is a valid YAML frontmatter and links should work as well

**Comment by Trikzon** [comment]
Huh, I thought I tested this and found that it wasn't valid YAML... but I just checked and it is.
I'll review your PR and look into getting it merged soon

**Comment by Trikzon** [comment]
I haven't looked at your PR yet, but I might choose to get rid of supporting links within quotes since this works.
