### ISSUE TITLE
A few quirks

### ISSUE THREAD

**Issue by abdcef** [Trikzon/obsidian-frontmatter-links#8]
Thanks for this plugin!
- Is it possible to get rid of the quotes when adding [[..]] links in yaml? 
- I still get invalid metadata in the preview mode. Can the plugin help fix this?
- Linked mentions do not recognize links in the front matter. Can these be fixed?
Sorry for the long list!!

**Comment by Trikzon** [comment]
> Is it possible to get rid of the quotes when adding [[..]] links in yaml?

Do you mean do something like:
```
---
link: [[Example]]
---
```
If so, then no you can't because YAML doesn't parse that correctly. It requires quotes around those links.

> I still get invalid metadata in the preview mode. Can the plugin help fix this?

I'm not sure what you mean.

> Linked mentions do not recognize links in the front matter. Can these be fixed?

I would like to get this fixed soon. That should be solved in #2

**Comment by abdcef** [comment]
> > I still get invalid metadata in the preview mode. Can the plugin help fix this?
> 
> I'm not sure what you mean.

Just realized that this doesn’t work on the mobile version. So I’m unable to take a screenshot. But when I change to preview mode, the yaml gives an invalid metadata error. I will try upload a screenshot later.

Thanks for looking at the other two issues.

**Comment by Trikzon** [comment]
> Just realized that this doesn’t work on the mobile version. So I’m unable to take a screenshot. But when I change to preview mode, the yaml gives an invalid metadata error. I will try upload a screenshot later.

This might be fixed in the version that will be released later today, but you can watch #10 for updates.

> I still get invalid metadata in the preview mode. Can the plugin help fix this?

Please make a new issue when you're able to load it on mobile (or desktop) and include a screenshot.

> Linked mentions do not recognize links in the front matter. Can these be fixed?

This actually won't be fixed with #2 as it seems Obsidian uses a different system for backlinks than the graph. I will fix it in the future and have created a new issue for it #11
